apiVersion: v1
kind: ServiceAccount
metadata:
  name: kraftnetes-engine-service-account
  namespace: kraftnetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-service-manager-role
  namespace: kraftnetes-servers
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-service-manager-binding
  namespace: kraftnetes-servers
subjects:
  - kind: ServiceAccount
    name: kraftnetes-engine-service-account
    namespace: kraftnetes
roleRef:
  kind: Role
  name: job-service-manager-role
  apiGroup: rbac.authorization.k8s.io