name: GitOps CI/CD Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kustomize
        run: |
          mkdir -p bin
          curl -sL https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize-linux-amd64 -o bin/kustomize
          chmod +x bin/kustomize
          echo "$(pwd)/bin" >> $GITHUB_PATH
          kustomize version

      - name: Validate Kustomizations
        run: |
          find . -name 'kustomization.yaml' | while read -r file; do
            echo "Validating $file"
            dir=$(dirname "$file")
            kustomize build --validate "$dir" >/dev/null || {
              echo "Validation failed in $dir"; exit 1;
            }
          done

  kubeconform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kustomize and kubeconform
        run: |
          mkdir -p bin
          curl -sL https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize-linux-amd64 -o bin/kustomize
          curl -sL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64 -o bin/kubeconform
          chmod +x bin/kustomize bin/kubeconform
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run kubeconform
        run: |
          find . -name 'kustomization.yaml' | while read -r file; do
            echo "Testing $file"
            dir=$(dirname "$file")
            kustomize build "$dir" | kubeconform -strict -summary || {
              echo "Kubeconform validation failed in $dir"; exit 1;
            }
          done
